controller_manager:
  ros__parameters:
    update_rate: 500  # Hz

    system_steering_controller:
      type: position_controllers/JointGroupPositionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

system_steering_controller:
  ros__parameters:
    joints:
      - steering_joint